### ISSUE TITLE
ajax를 이용한 댓글구현 에러 해결

### ISSUE THREAD

**Issue by kyupid** [Jiwon-JJW/spring-boot-qna#13]
Uncaught TypeError: Cannot read property 'id' of undefined
    at Object.ok [as success] (scripts.js:30)

Quesitond에 answers에 있는 `@JsonIgnroe` 을없애고 Answer에 있는 question에 `@JsonProperty`를 넣어줬더니 동작함

**Comment by Jiwon-JJW** [comment]
추측 -> JsonProperty로는 변수의 값들을 읽어낼 수 있지만, JsonIgnroe는 읽어낼 수 없기 때문으로 추측!

**Comment by kyupid** [comment]
댓글을 달면 실시간으로 생기는데 새로고침하면 다 사라지는 문제 ->>>>>


쇼에다가 머스태치로퀘스쳔포문을 다 감싸서 돌렸는데 그걸빼고 퀘스쳔.롸이터.타이틀 했떠니
문제가 생겼다
그걸 적용했떠니?
MJ(백엔드) to Everyone (21:38)
그렇군요
Me to Everyone (21:39)
안에있는 엔쓰월리스트의 포문을 못도니까
문제가생겻다
