### ISSUE TITLE
미션4 리뷰 좀 걱정되는 부분

### ISSUE THREAD

**Issue by kyupid** [Jiwon-JJW/spring-boot-qna#15]
이 부분 적용해야할 게 많네요 ㅠㅠ

https://github.com/codesquad-members-2021/spring-boot-qna/pull/113#discussion_r601432412

4단계까지 왔으니까 추가적으로 학습을 하나 진행해볼까요.
여기서 questionRepository.save() 없이 변경 내용을 Question 에 반영하는 방법을 알아보세요.

힌트

@Transactional
EntityManager
PersistenceContext

**Comment by kyupid** [comment]
넵 아까 얘기했던대로 마지막에 차근히 공부해봅시다

**Comment by wheejuni** [comment]
구경 왔습니다. 학습은 다 마치셨나요? 어떠셨어요?
